/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Bishop_R.glb')
  const material = nodes.mesh_0.material.clone();
  material.color.setRGB(props.rgb.r,props.rgb.g,props.rgb.b)
  return (
    <group ref={group} {...props} dispose={null}>
            <group scale={[0.02, 0.02, 0.02]}>

      <mesh geometry={nodes.mesh_0.geometry} material={material} />
      </group>
    </group>
  )
}

useGLTF.preload('/Bishop_R.glb')
