/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Pawn.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Box_1.geometry} material={materials['Butterfly Wing']} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.Box.geometry} material={materials['Diamond Dust']} position={[0, 0.06, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
    </group>
  )
}

useGLTF.preload('/Pawn.gltf')
